name: job-portal-backend

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    image: job-portal-backend:latest
    container_name: job-portal-backend
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_WEBHOOK_SECRET: ${SUPABASE_WEBHOOK_SECRET}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_RESUME_BUCKET: ${SUPABASE_RESUME_BUCKET}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - '3000:3000'

volumes:
  pgdata:
