export enum EnvKey {
  NODE_ENV = 'NODE_ENV',

  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DB = 'POSTGRES_DB',

  SUPABASE_URL = 'SUPABASE_URL',
  SUPABASE_WEBHOOK_SECRET = 'SUPABASE_WEBHOOK_SECRET',
}
