export enum EnvKey {
  NODE_ENV = 'NODE_ENV',

  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DB = 'POSTGRES_DB',

  SUPABASE_URL = 'SUPABASE_URL',
  SUPABASE_WEBHOOK_SECRET = 'SUPABASE_WEBHOOK_SECRET',
  SUPABASE_SERVICE_ROLE_KEY = 'SUPABASE_SERVICE_ROLE_KEY',
  SUPABASE_RESUME_BUCKET = 'SUPABASE_RESUME_BUCKET',

  THROTTLE_TTL = 'THROTTLE_TTL',
  THROTTLE_LIMIT = 'THROTTLE_LIMIT',

  // Comma-separated list of allowed CORS origins, e.g.
  // "http://localhost:5173,https://app.example.com". Unset or empty reflects
  // the request origin (dev-friendly); "*" allows any origin.
  CORS_ORIGINS = 'CORS_ORIGINS',
}
